language: python

deploy:
  provider: pypi
  distributions: sdist
  user: mhugo
  password:
    secure: WRIHtbW/KixCpjpn+j7xZPZPYCsoERI4+BweZZdKYDzH1tJnMdfLqpAA+8Sj7mBPHpVmdpItdRSB26dZP9eGn1v9jtY5V7L2uIFH9iwd92nouq2WKs3j8a8c0yy0pL1wJ4Ttf5v7Wf+RZK/RRa052GboMEDW5GqROsyMjaxZnAFwQ0syXq/vEIzkyI/3F5QMX/b2VgduulP6VbC6WdCKEgncPIh9CVaOiqe55DMWEXylHqfFxsAqLcJXI/cStwMycWAqyvIvzIhZudl5RjMw/k9551N0AiKL7MC0JQlKFbKXg4VV1b8Cn9fsMA2Pdcym5WBs2Mp8DZRxkxXHKzQxdlTcMF9mXKH4O6WqxO5Yop/43DyHHU+STa1UcXiK59Ia0h7gw2CYyW2CkDFDZrcGNwsL3K3sFKi0vRY6kxFGtMezqIQp3/BWkq7Q4LMEa2O9bP8W1Aukx307HdjIrFTNfMZIGTr4kzw+x/wB6FmlEemGL7aJTyf127uvTOhcelEPdpZB9nLVjnFpsayg7BJ10npboRiPgM0gfUkYtKg9KRi6uErbdASapCXwrHW2oDOmpbH/CyIzH18EU/0cGFYpcrlcbhIMfSR1lWWLtuHtRVOXFspU0H2xUWZLJvFOo8FgsvrhvwF1eDf6YK0anJkjXXbEoVU2fgTCVsSPZa4alc8=
  on:
    tags: true
    repo: Oslandia/pglite
